<div class="form-group"><label>Departemen</label>
    <select required name="departemen" id="departemen">
        <option disabled selected>-</option>
        <!-- <option value="1">Agribisnis</option>
        <option value="2">Keteknikan Pertanian</option>
        <option value="3">Ilmu & Teknologi Pangan</option>
        <option value="4">Agroteknologi</option>
        <option value="5">Ilmu Politik</option>
        <option value="6">Ilmu Pemerintahan</option>
        <option value="7">Ilmu Hubungan Internasional</option>
        <option value="8">Ilmu Komunikasi</option>
        <option value="9">Ilmu Administrasi</option>
        <option value="10">Sosiologi</option>
        <option value="11">Antropologi</option>
        <option value="12">Sastra Indonesia</option>
        <option value="13">Sastra Arab</option>
        <option value="14">Sastra Inggris</option>
        <option value="15">Ilmu Sejarah</option>
        <option value="16">Sastra Daerah</option>
        <option value="17">Arkeologi</option>
        <option value="18">Sastra Jepang</option>
        <option value="19">Ilmu Ekonomi</option>
        <option value="20">Manajemen</option>
        <option value="21">Akuntansi</option>
        <option value="22">Ilmu Hukum</option>
        <option value="23">Ilmu Administrasi Negara</option>
        <option value="24">Farmasi</option>
        <option value="25">Kedokteran Gigi</option>
        <option value="26">Matematika</option>
        <option value="27">Biologi</option>
        <option value="28">Fisika</option>
        <option value="29">Kimia</option>
        <option value="30">Geofisika</option>
        <option value="31">Statistika</option>
        <option value="32">Kehutanan</option>
        <option value="33">Peternakan</option> -->
        <option value="34">Teknik Elektro</option>
        <option value="35">Teknik Informatika</option>
        <option value="36">Teknik Sipil</option>
        <option value="37">Teknik Lingkungan</option>
        <option value="38">Teknik Mesin</option>
        <option value="39">Teknik Industri</option>
        <option value="40">Teknik Perkapalan</option>
        <option value="41">Teknik Kelautan</option>
        <option value="42">Teknik Sistem Perkapalan</option>
        <option value="43">Teknik Arsitektur</option>
        <option value="44">Teknik Perancangan Wilayah & Kota</option>
        <option value="45">Teknik Geologi</option>
        <option value="46">Teknik Pertambangan</option>
        <!-- <option value="47">Ilmu Kelautan</option>
        <option value="48">Perikanan</option>
        <option value="49">Kesehatan Masyarakat</option>
        <option value="50">Ilmu Kedokteran</option>
        <option value="51">Ilmu Keperawatan</option>
        <option value="52">Fisioterapi</option>
        <option value="53">Psikologi</option>
        <option value="54">Kedokteran Hewan</option> -->
    </select>
</div>